server:
  port: 8080

spring:
  application:
    name: paperless-rest
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/paperless}
    username: ${DB_USER:paperless}
    password: ${DB_PASSWORD:paperless}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    at.fhtw.swen3.paperless: INFO
